#!/bin/bash
# Croi AI Workforce Platform - Project Structure Generator
# Run this script from the croi/ root directory.
# Creates all directories and empty placeholder files. No code content is added.

set -e

echo "Creating Croi project structure..."

# ---------- FRONTEND ----------
mkdir -p "frontend/app/(auth)/login"
mkdir -p "frontend/app/(auth)/signup"
mkdir -p "frontend/app/(dashboard)/chat"
mkdir -p "frontend/app/(dashboard)/conversations"
mkdir -p "frontend/app/(dashboard)/settings"
mkdir -p "frontend/app/api"
mkdir -p "frontend/components/auth"
mkdir -p "frontend/components/chat"
mkdir -p "frontend/components/conversations"
mkdir -p "frontend/components/layout"
mkdir -p "frontend/components/common"
mkdir -p "frontend/components/ui"
mkdir -p "frontend/hooks"
mkdir -p "frontend/services"
mkdir -p "frontend/lib"
mkdir -p "frontend/types"
mkdir -p "frontend/styles"

touch "frontend/app/(auth)/login/page.tsx"
touch "frontend/app/(auth)/signup/page.tsx"
touch "frontend/app/(auth)/layout.tsx"
touch "frontend/app/(dashboard)/chat/page.tsx"
touch "frontend/app/(dashboard)/conversations/page.tsx"
touch "frontend/app/(dashboard)/settings/page.tsx"
touch "frontend/app/(dashboard)/layout.tsx"
touch "frontend/app/layout.tsx"
touch "frontend/app/page.tsx"
touch "frontend/app/globals.css"
touch "frontend/app/api/.gitkeep"

touch "frontend/components/auth/LoginForm.tsx"
touch "frontend/components/auth/SignupForm.tsx"
touch "frontend/components/auth/LogoutButton.tsx"
touch "frontend/components/chat/ChatWindow.tsx"
touch "frontend/components/chat/MessageList.tsx"
touch "frontend/components/chat/MessageInput.tsx"
touch "frontend/components/chat/MessageBubble.tsx"
touch "frontend/components/conversations/ConversationList.tsx"
touch "frontend/components/conversations/ConversationItem.tsx"
touch "frontend/components/conversations/NewConversationButton.tsx"
touch "frontend/components/layout/Header.tsx"
touch "frontend/components/layout/Sidebar.tsx"
touch "frontend/components/layout/Footer.tsx"
touch "frontend/components/common/Button.tsx"
touch "frontend/components/common/Input.tsx"
touch "frontend/components/common/Modal.tsx"
touch "frontend/components/common/Loader.tsx"
touch "frontend/components/common/ErrorBoundary.tsx"
touch "frontend/components/ui/.gitkeep"

touch "frontend/hooks/useAuth.ts"
touch "frontend/hooks/useChat.ts"
touch "frontend/hooks/useConversations.ts"
touch "frontend/hooks/useApi.ts"

touch "frontend/services/authService.ts"
touch "frontend/services/chatService.ts"
touch "frontend/services/conversationService.ts"
touch "frontend/services/apiClient.ts"

touch "frontend/lib/api.ts"
touch "frontend/lib/auth.ts"
touch "frontend/lib/utils.ts"

touch "frontend/types/auth.ts"
touch "frontend/types/chat.ts"
touch "frontend/types/conversation.ts"
touch "frontend/types/api.ts"

touch "frontend/styles/.gitkeep"

touch "frontend/.env.local"
touch "frontend/.env.example"
touch "frontend/next.config.js"
touch "frontend/tailwind.config.ts"
touch "frontend/tsconfig.json"
touch "frontend/package.json"
touch "frontend/README.md"

# ---------- BACKEND ----------
mkdir -p "backend/src/main/java/com/croi/config"
mkdir -p "backend/src/main/java/com/croi/security"
mkdir -p "backend/src/main/java/com/croi/common/exception"
mkdir -p "backend/src/main/java/com/croi/common/dto"
mkdir -p "backend/src/main/java/com/croi/common/constants"
mkdir -p "backend/src/main/java/com/croi/common/utils"
mkdir -p "backend/src/main/java/com/croi/auth/controller"
mkdir -p "backend/src/main/java/com/croi/auth/dto"
mkdir -p "backend/src/main/java/com/croi/auth/service"
mkdir -p "backend/src/main/java/com/croi/users/controller"
mkdir -p "backend/src/main/java/com/croi/users/entity"
mkdir -p "backend/src/main/java/com/croi/users/dto"
mkdir -p "backend/src/main/java/com/croi/users/repository"
mkdir -p "backend/src/main/java/com/croi/users/service"
mkdir -p "backend/src/main/java/com/croi/organization/controller"
mkdir -p "backend/src/main/java/com/croi/organization/entity"
mkdir -p "backend/src/main/java/com/croi/organization/dto"
mkdir -p "backend/src/main/java/com/croi/organization/repository"
mkdir -p "backend/src/main/java/com/croi/organization/service"
mkdir -p "backend/src/main/java/com/croi/conversation/controller"
mkdir -p "backend/src/main/java/com/croi/conversation/entity"
mkdir -p "backend/src/main/java/com/croi/conversation/dto"
mkdir -p "backend/src/main/java/com/croi/conversation/repository"
mkdir -p "backend/src/main/java/com/croi/conversation/service"
mkdir -p "backend/src/main/java/com/croi/conversation/event"
mkdir -p "backend/src/main/java/com/croi/knowledge/controller"
mkdir -p "backend/src/main/java/com/croi/knowledge/entity"
mkdir -p "backend/src/main/java/com/croi/knowledge/dto"
mkdir -p "backend/src/main/java/com/croi/knowledge/repository"
mkdir -p "backend/src/main/java/com/croi/knowledge/service"
mkdir -p "backend/src/main/java/com/croi/knowledge/parser"
mkdir -p "backend/src/main/java/com/croi/ai/agents"
mkdir -p "backend/src/main/java/com/croi/ai/providers/openai/dto"
mkdir -p "backend/src/main/java/com/croi/ai/prompts"
mkdir -p "backend/src/main/java/com/croi/ai/memory"
mkdir -p "backend/src/main/java/com/croi/ai/tools"
mkdir -p "backend/src/main/java/com/croi/ai/guardrails"
mkdir -p "backend/src/main/java/com/croi/ai/models"
mkdir -p "backend/src/main/java/com/croi/ai/service"
mkdir -p "backend/src/main/java/com/croi/communication/controller"
mkdir -p "backend/src/main/java/com/croi/communication/dto"
mkdir -p "backend/src/main/java/com/croi/communication/service"
mkdir -p "backend/src/main/resources/db/migration"
mkdir -p "backend/src/test/java/com/croi/auth"
mkdir -p "backend/src/test/java/com/croi/users"
mkdir -p "backend/src/test/java/com/croi/conversation"
mkdir -p "backend/src/test/java/com/croi/ai"
mkdir -p "backend/src/test/java/com/croi/common"
mkdir -p "backend/src/test/resources"

touch "backend/src/main/java/com/croi/CroiApplication.java"

touch "backend/src/main/java/com/croi/config/SecurityConfig.java"
touch "backend/src/main/java/com/croi/config/JwtConfig.java"
touch "backend/src/main/java/com/croi/config/OpenApiConfig.java"
touch "backend/src/main/java/com/croi/config/CorsConfig.java"
touch "backend/src/main/java/com/croi/config/DatabaseConfig.java"

touch "backend/src/main/java/com/croi/security/JwtProvider.java"
touch "backend/src/main/java/com/croi/security/JwtFilter.java"
touch "backend/src/main/java/com/croi/security/UserPrincipal.java"
touch "backend/src/main/java/com/croi/security/AuthenticationProvider.java"
touch "backend/src/main/java/com/croi/security/CustomUserDetailsService.java"

touch "backend/src/main/java/com/croi/common/exception/ApiException.java"
touch "backend/src/main/java/com/croi/common/exception/ResourceNotFoundException.java"
touch "backend/src/main/java/com/croi/common/exception/UnauthorizedException.java"
touch "backend/src/main/java/com/croi/common/exception/GlobalExceptionHandler.java"
touch "backend/src/main/java/com/croi/common/dto/ApiResponse.java"
touch "backend/src/main/java/com/croi/common/dto/ApiError.java"
touch "backend/src/main/java/com/croi/common/dto/PaginatedResponse.java"
touch "backend/src/main/java/com/croi/common/constants/ApiConstants.java"
touch "backend/src/main/java/com/croi/common/constants/ErrorMessages.java"
touch "backend/src/main/java/com/croi/common/utils/ValidationUtils.java"
touch "backend/src/main/java/com/croi/common/utils/DateUtils.java"

touch "backend/src/main/java/com/croi/auth/controller/AuthController.java"
touch "backend/src/main/java/com/croi/auth/dto/LoginRequest.java"
touch "backend/src/main/java/com/croi/auth/dto/SignupRequest.java"
touch "backend/src/main/java/com/croi/auth/dto/AuthResponse.java"
touch "backend/src/main/java/com/croi/auth/service/AuthService.java"

touch "backend/src/main/java/com/croi/users/controller/UserController.java"
touch "backend/src/main/java/com/croi/users/entity/User.java"
touch "backend/src/main/java/com/croi/users/dto/UserDto.java"
touch "backend/src/main/java/com/croi/users/dto/UserProfileUpdateRequest.java"
touch "backend/src/main/java/com/croi/users/repository/UserRepository.java"
touch "backend/src/main/java/com/croi/users/service/UserService.java"

touch "backend/src/main/java/com/croi/organization/controller/OrganizationController.java"
touch "backend/src/main/java/com/croi/organization/entity/Organization.java"
touch "backend/src/main/java/com/croi/organization/entity/OrganizationMember.java"
touch "backend/src/main/java/com/croi/organization/dto/OrganizationDto.java"
touch "backend/src/main/java/com/croi/organization/dto/CreateOrganizationRequest.java"
touch "backend/src/main/java/com/croi/organization/repository/OrganizationRepository.java"
touch "backend/src/main/java/com/croi/organization/repository/OrganizationMemberRepository.java"
touch "backend/src/main/java/com/croi/organization/service/OrganizationService.java"

touch "backend/src/main/java/com/croi/conversation/controller/ConversationController.java"
touch "backend/src/main/java/com/croi/conversation/entity/Conversation.java"
touch "backend/src/main/java/com/croi/conversation/entity/Message.java"
touch "backend/src/main/java/com/croi/conversation/dto/ConversationDto.java"
touch "backend/src/main/java/com/croi/conversation/dto/MessageDto.java"
touch "backend/src/main/java/com/croi/conversation/dto/CreateConversationRequest.java"
touch "backend/src/main/java/com/croi/conversation/dto/SendMessageRequest.java"
touch "backend/src/main/java/com/croi/conversation/repository/ConversationRepository.java"
touch "backend/src/main/java/com/croi/conversation/repository/MessageRepository.java"
touch "backend/src/main/java/com/croi/conversation/service/ConversationService.java"
touch "backend/src/main/java/com/croi/conversation/event/.gitkeep"

touch "backend/src/main/java/com/croi/knowledge/controller/DocumentController.java"
touch "backend/src/main/java/com/croi/knowledge/entity/Document.java"
touch "backend/src/main/java/com/croi/knowledge/entity/DocumentEmbedding.java"
touch "backend/src/main/java/com/croi/knowledge/dto/DocumentDto.java"
touch "backend/src/main/java/com/croi/knowledge/dto/UploadDocumentRequest.java"
touch "backend/src/main/java/com/croi/knowledge/repository/DocumentRepository.java"
touch "backend/src/main/java/com/croi/knowledge/repository/DocumentEmbeddingRepository.java"
touch "backend/src/main/java/com/croi/knowledge/service/DocumentService.java"
touch "backend/src/main/java/com/croi/knowledge/service/PdfParsingService.java"
touch "backend/src/main/java/com/croi/knowledge/service/EmbeddingService.java"
touch "backend/src/main/java/com/croi/knowledge/parser/PdfParser.java"

touch "backend/src/main/java/com/croi/ai/agents/CustomerSupportAgent.java"
touch "backend/src/main/java/com/croi/ai/agents/AgentContext.java"
touch "backend/src/main/java/com/croi/ai/providers/AIProvider.java"
touch "backend/src/main/java/com/croi/ai/providers/openai/OpenAIProvider.java"
touch "backend/src/main/java/com/croi/ai/providers/openai/OpenAIConfig.java"
touch "backend/src/main/java/com/croi/ai/providers/openai/dto/OpenAIRequest.java"
touch "backend/src/main/java/com/croi/ai/providers/openai/dto/OpenAIResponse.java"
touch "backend/src/main/java/com/croi/ai/prompts/PromptTemplate.java"
touch "backend/src/main/java/com/croi/ai/prompts/CustomerSupportPrompts.java"
touch "backend/src/main/java/com/croi/ai/memory/ConversationMemory.java"
touch "backend/src/main/java/com/croi/ai/memory/MemoryStore.java"
touch "backend/src/main/java/com/croi/ai/tools/.gitkeep"
touch "backend/src/main/java/com/croi/ai/guardrails/.gitkeep"
touch "backend/src/main/java/com/croi/ai/models/AIMessage.java"
touch "backend/src/main/java/com/croi/ai/models/AIResponse.java"
touch "backend/src/main/java/com/croi/ai/service/AIService.java"

touch "backend/src/main/java/com/croi/communication/controller/ChatController.java"
touch "backend/src/main/java/com/croi/communication/dto/ChatRequest.java"
touch "backend/src/main/java/com/croi/communication/dto/ChatResponse.java"
touch "backend/src/main/java/com/croi/communication/service/ChatService.java"

touch "backend/src/main/resources/application.yml"
touch "backend/src/main/resources/application-dev.yml"
touch "backend/src/main/resources/application-prod.yml"
touch "backend/src/main/resources/db/migration/V1__Initial_Schema.sql"
touch "backend/src/main/resources/db/migration/V2__Create_Users.sql"
touch "backend/src/main/resources/db/migration/V3__Create_Organizations.sql"
touch "backend/src/main/resources/db/migration/V4__Create_Conversations.sql"
touch "backend/src/main/resources/db/migration/V5__Create_Knowledge.sql"

touch "backend/src/test/java/com/croi/auth/.gitkeep"
touch "backend/src/test/java/com/croi/users/.gitkeep"
touch "backend/src/test/java/com/croi/conversation/.gitkeep"
touch "backend/src/test/java/com/croi/ai/.gitkeep"
touch "backend/src/test/java/com/croi/common/.gitkeep"
touch "backend/src/test/resources/application-test.yml"

touch "backend/pom.xml"
touch "backend/.gitignore"
touch "backend/Dockerfile"
touch "backend/README.md"

# ---------- DOCKER & SCRIPTS ----------
mkdir -p "docker"
mkdir -p "scripts"

touch "docker/Dockerfile.backend"
touch "docker/Dockerfile.frontend"
touch "docker/nginx.conf"

touch "scripts/setup.sh"
touch "scripts/build.sh"
touch "scripts/start-dev.sh"
touch "scripts/migrate-db.sh"
chmod +x scripts/setup.sh scripts/build.sh scripts/start-dev.sh scripts/migrate-db.sh

# ---------- DOCS & ROOT ----------
mkdir -p "docs"

touch "docs/ARCHITECTURE.md"
touch "docs/API.md"
touch "docs/DATABASE.md"
touch "docs/SETUP.md"
touch "docs/DEPLOYMENT.md"
touch "docs/AI_DESIGN.md"

touch "docker-compose.yml"
touch "docker-compose.dev.yml"
touch ".env.example"
touch ".gitignore"
touch "README.md"
touch "LICENSE"

echo "Croi project structure created successfully."
